Assign tag for digests
ietf-rats-wg/draft-ietf-rats-corim pull request #203
Opened 2024-02-12 15:31 UTC by andrew-draper

Issue #154 notes that there is no tag assigned for a digests measurement when it appears at a local codepoint (for example at measurement-values-map codepoint -42).

This diff allocates the next available codepoint to inform the verifier that it should use the digests type.

2024-02-14 15:58 UTC, yogeshbdeshpande approved these changes
LGTM!

2024-02-16 19:09 UTC, nedmsmith commented on draft-ietf-rats-corim.md
> +The `digests-type-choice` measurement is either an untagged array of `digest` or the same array tagged with the CBOR tag `#6.562`.
```suggestion
The `digests-type-choice` measurement is either an untagged array of `digest` or the same array tagged with the CBOR tag `#6.562`.
If a usage of `digests` differs from the semantics described for `#6.562`, then a different CBOR tag value MUST be used that defines the different semantics such that verifiers can agree to correct processing behavior.
```

2024-02-17 12:12 UTC, thomas-fossati requested changes
I am afraid I don't understand the goal of this PR.
The issue too is quite cryptic.

2024-02-17 19:48 UTC, nedmsmith commented
> I am afraid I don't understand the goal of this PR. The issue too is quite cryptic.

There are 3 ways to disambiguate semantics of a right-hand-side (RHS) expression. Profiles, code points (LHS), CBOR tags (RHS). Profiles, code points, and CBOR tags all have vendor-specific alternatives, that if used, require vendor-specific updates to Verifiers. Given the goal of a universal verifier is to avoid vendor-specific updates, standard profiles (e.g., DICE / base CoMID), positive code points, and standard CBOR tags `#6.<0..32767>` must be used.

A while back we argued ourselves out of `[ + measurement-values-map ]` multiplicity. However, if there is a need for multiple measurements of the same type e.g., `digests`. There are 4 ways to do that. 
(1) multiple triple entries where the `environment-map` is repeated for each different `measurement-map`.
(2) use multiple but different code points.
(3) define a new measurement type that includes multiplicity on the RHS i.e., `[ + RHS ]`, e.g., `integrity-registers`. 
(4) add back multiplicity around `measurement-values-map`.

Option (1) seems to create bloat by repeating the `environment-map` multiple times. But verifiers might not preserve ordering, hence could get the entries reversed. So, not a realistic option.
Option (4) still requires positional logic to disambiguate individual instances. Hence, some other form of index value is needed that is recognized by universal verifiers. So, not a realistic option.
Option (3) requires an update to a standard for each new instance of the measurement. Flexibility could be an issue.
Option (2) was discussed a few times and there seemed to be consensus for its use. But non-vendor specific CBOR tags are needed for the RHS to ensure a universal verifier can process multiples. Nevertheless, (unless I'm mistaken) the CDDL that defines the negative code points has to be defined, possibly via a profile? 
But more generally, it could be defined by reserving a few LHS code points that expect `#6.<0..32767>(any)` or maybe `#6.<500..599>(any)` as the RHS value?  E.g.:
```
measurement-values-map = {
    ? < -25..-1 > => #6.<500..599>(any)
}
```

2024-02-19 18:25 UTC, nedmsmith commented
The CBOR code point defines a standardized structure such as ‘digests’.

Sent from my iPhone

On Feb 19, 2024, at 4:55 AM, Thomas Fossati ***@***.***> wrote:

﻿

measurement-values-map = {
    ? < -25..-1 > => #6.<500..599>(any)
}


Even so, you'd need a profile to tell the verifier what -25 and 599 mean.

—
Reply to this email directly, view it on GitHub<https://github.com/ietf-rats-wg/draft-ietf-rats-corim/pull/203#issuecomment-1952395060>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABPMCSGB4WWWKMTLDLYZFE3YUNDVDAVCNFSM6AAAAABDE5VJ2KVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNJSGM4TKMBWGA>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2024-05-01 18:09 UTC, nedmsmith commented
Section 1.3.8 contains a description of a singleton digest but also says `A measurement can be obtained using different hash algorithms. A digests-type can be used to collect multiple digest values obtained by applying different hash algorithms on the same input.` Arguably, this statement belongs in section 3.1.4.1.5.2 measurement-values-map where the semantics of code point 2 are described. Because the multiple digests describe the same object, code point 2 is an algorithm agility capability where some implementations may use one hash algorithm while another may use something different. 

If there is another use case for multiple digests, then we should document it and assign a code point for it. 

Additionally, it might make sense for the second usage to require algorithm agility properties, in which case the structure might need to be an array of arrays? (e.g. `integrity-registers`).

Otherwise, this PR becomes a request for an extensibility point on code point 2 which seems nuanced and subtle when taken in the context of all the other possible ways to extend.

2024-07-03 14:37 UTC, thomas-fossati commented
@andrew-draper to file an issue discussing extension points and data types, that can be discussed before a new PR is created.

2024-07-03 14:37 UTC, closed without merging