Fix wrong registry reference.
ietf-rats-wg/draft-ietf-rats-corim pull request #213
Opened 2024-03-07 10:33 UTC by thomas-fossati

2024-03-07 17:18 UTC, nedmsmith approved these changes
LGTM

2024-03-07 17:22 UTC, yogeshbdeshpande approved these changes
LGTM!

2024-03-08 16:37 UTC, henkbirkholz requested changes
Is it the wrong one, though?

2024-03-08 17:05 UTC, thomas-fossati commented on draft-ietf-rats-corim.md
> +The `int` encoding is RECOMMENDED.
```suggestion
Whenever possible, using the `int` encoding is RECOMMENDED.
```

2024-03-08 19:21 UTC, nedmsmith approved these changes
LGTM

2024-03-11 16:01 UTC, henkbirkholz approved these changes

2024-03-27 15:22 UTC, merged