Update draft-ietf-rats-corim.md
ietf-rats-wg/draft-ietf-rats-corim pull request #270
Opened 2024-09-13 19:31 UTC by nedmsmith

Combined sections 5, 6 and 7 and provided prose for the new section.

2024-09-15 01:03 UTC, deeglaze requested changes

2024-09-15 01:03 UTC, deeglaze commented on draft-ietf-rats-corim.md
> +An internal representation of Attestation Results as separate contexts, (see {{sec-ir-ars}}), ensures Relying Party specific processing doesn't modify the ACS, which is common to all Relying Parties.
```suggestion
An internal representation of Attestation Results as separate contexts (see {{sec-ir-ars}}) ensures Relying Party–specific processing does not modify the ACS, which is common to all Relying Parties.
```
Parentheticals aren't also appositives.

I don't see how the sec-ir-ars reference elaborates the description of [ + ECT ] as "separate contexts". It's just another data definition that's equivalent to an ACS.

I don't think we've specified that the ACS is common to all relying parties either. There's nothing about the data definition that "ensures processing doesn't modify" something else. It's an organization technique that may help with that, but I don't know what this text is trying to say.

2024-09-17 22:53 UTC, deeglaze approved these changes

2024-09-18 11:45 UTC, thomas-fossati approved these changes
LGTM

(A few typo fixes in-line.)

2024-09-18 11:45 UTC, thomas-fossati commented on draft-ietf-rats-corim.md
> +Claims related to Verifier applied consistency checks are asserted under the authority of the Verifier.
```suggestion
Claims related to Verifier-applied consistency checks are asserted under the authority of the Verifier.
```

2024-09-18 11:45 UTC, thomas-fossati commented on draft-ietf-rats-corim.md
> +For example, the `attest-key-triple-record` may contain a cryptographic key to which the Verifier applies certificate path construction and verification.
```suggestion
For example, the `attest-key-triple-record` may contain a cryptographic key to which the Verifier applies certificate path construction and validation.
```

2024-09-18 11:45 UTC, thomas-fossati commented on draft-ietf-rats-corim.md
> +The verification result may reveal an expired certificate.
```suggestion
Validation may reveal an expired certificate.
```

2024-09-18 11:45 UTC, thomas-fossati commented on draft-ietf-rats-corim.md
> +An internal representation of policy details, based on the policy ECT as described in {{sec-ir-policy}}, contain the environments affected by the policy with policy identifiers as Claims.
```suggestion
An internal representation of policy details, based on the policy ECT as described in {{sec-ir-policy}}, contains the environments affected by the policy with policy identifiers as Claims.
```

2024-09-18 14:10 UTC, henkbirkholz approved these changes

2024-09-18 14:11 UTC, yogeshbdeshpande approved these changes
LGTM!

2024-09-18 14:11 UTC, merged