Move contributors to front matter
ietf-rats-wg/draft-ietf-rats-corim pull request #305
Opened 2024-10-04 15:07 UTC by deeglaze

There is an extraneous Contributors section that went unnoticed since there was also a typographical mistake that demoted the section heading to normal text.

2024-10-04 15:11 UTC, thomas-fossati requested changes
I disagree with this PR.  Given the substantial and continuous contributions to the spec, both Dionna and Andy should be listed as co-authors rather than contributors.

2024-10-04 15:56 UTC, nedmsmith approved these changes
LGTM

2024-10-04 16:06 UTC, thomas-fossati approved these changes
I am OK with contributors (for now).

I want to have the discussion with the RATS chairs in Dublin to allow >5 editors.

2024-10-07 16:48 UTC, yogeshbdeshpande approved these changes
Thanks Dionna for the tidy up!

2024-10-07 16:50 UTC, merged