Add linear privilege level measurement value type
ietf-rats-wg/draft-ietf-rats-corim pull request #354
Opened 2024-12-18 16:46 UTC by deeglaze

As a means of representing a CPL or VMPL, this provides some extra semantic understanding. Leaving condition-matching to a later PR.

2025-01-22 13:28 UTC, yogeshbdeshpande commented
@deeglaze Instead of directly making a change request, can we please have an issue, which describes a requirement.

What is a Privilege level of an Environment ?

Why it is needed? What uses cases are relevant when this feature gains relevance ?

2025-01-22 15:45 UTC, deeglaze commented on draft-ietf-rats-corim.md
@andrew-draper requests this PR to contain a matching algorithm.

2025-01-22 15:46 UTC, deeglaze commented on draft-ietf-rats-corim.md
Also example diags.

2025-01-22 15:46 UTC, yogeshbdeshpande commented
Add matching rules to the PR

Add examples to the PR, in CDDL

2025-01-22 15:46 UTC, yogeshbdeshpande requested changes
Please continue good work on the PR

2025-01-22 15:50 UTC, deeglaze commented on draft-ietf-rats-corim.md
> +For environments that count privilege in the opposite order, it is recommended to represent the privilege levels with non-positive numbers, where 0 is the lowest privilege, and some negative integer
```suggestion
For environments that count privilege in the opposite order, it is recommended to represent the privilege levels with non-positive numbers, where 0 is the lowest privilege, and some negative integer is the highest.
The full range if signed integers may be used.
```

2025-01-29 12:48 UTC, yogeshbdeshpande commented
@deeglaze I assume, there is still work to be done on this PR, so we would not take this up during CoRIM Meeting on 29th Jan 2025 ?

2025-01-29 16:55 UTC, nedmsmith approved these changes
See inline comments

2025-01-29 16:55 UTC, nedmsmith commented on draft-ietf-rats-corim.md
> +The comparison MUST return true if the value of PRIV is greater than or equal to the `min` value in the condition ECT AND the value of PRIV is less or equal to than the `max` value in the condition E
```suggestion
The comparison MUST return true if the value of PRIV is greater than or equal to the `min` value in the condition ECT AND the value of PRIV is less than or equal to than the `max` value in the condition ECT
```

2025-01-30 23:52 UTC, nedmsmith approved these changes
LGTM

2025-01-30 23:53 UTC, nedmsmith submitted a review, later dismissed
LGTM

2025-02-05 14:48 UTC, yogeshbdeshpande commented on draft-ietf-rats-corim.md
> +A Linear Privilege Level describes an operating privilege for the target environment.
I would swap the bottom sentence to state that:

2025-02-05 14:49 UTC, yogeshbdeshpande commented on draft-ietf-rats-corim.md
> +A Linear Privilege Level describes an operating privilege for the target environment.
```suggestion
A Linear Privilege Level describes an operating privilege for the target environment. The privilege can be expressed in either positive integer ranges or in negative integer ranges.
```

2025-02-05 14:50 UTC, yogeshbdeshpande commented on draft-ietf-rats-corim.md
> +The convention is that 0 is the highest privilege, and higher numbers correspond to fewer privileges.
```suggestion
When expressed in positive integer ranges the convention is that 0 is the highest privilege, and higher numbers correspond to fewer privileges. No negative number representation is allowed, in this setting.
```

2025-02-05 14:51 UTC, yogeshbdeshpande commented on draft-ietf-rats-corim.md
> +If the entry `linear-privlevel-type-choice` is an `int` or an `int` tagged with #6.564, then comparison with the `int` named as PRIV is as follows.
I am not clear when was PRIV introduced and what its context is? Can you please clarify..

2025-02-05 14:52 UTC, deeglaze commented on draft-ietf-rats-corim.md
> +The convention is that 0 is the highest privilege, and higher numbers correspond to fewer privileges.
What setting? This is convention.

2025-02-05 14:52 UTC, yogeshbdeshpande commented on draft-ietf-rats-corim.md
> +*  If the condition ECT value for `measurement-values-map` codepoint 15 is an untagged `int` or an `int` tagged with #6.564 then an equality comparison is performed on the `int` components.
When would one use `int` and whan would one use `tagged-int`. can you please explain as this is the base spec!

2025-02-05 14:54 UTC, yogeshbdeshpande commented on cddl/linear-privilege-level.cddl
> +int-range = [min: inf-int, max: inf-int]
This looks like a policy construct which i am little nervous in absorbing here..?

is there a way to express it more clearly using base types?

2025-02-05 14:54 UTC, yogeshbdeshpande reviewed
Made some comments!

2025-02-12 04:51 UTC, deeglaze commented on draft-ietf-rats-corim.md
> +The convention is that 0 is the highest privilege, and higher numbers correspond to fewer privileges.
I don't understand this comment. Replace what with convention? I'm trying to encode a range comparison that requires an internalized notion of order.

2025-02-12 04:54 UTC, deeglaze commented on draft-ietf-rats-corim.md
> +If the entry `linear-privlevel-type-choice` is an `int` or an `int` tagged with #6.564, then comparison with the `int` named as PRIV is as follows.
PRIV is referenced below when describing the comparison. PRIV here represents an exact privilege level in the ACS that will be compared against a CoRIM. I'm following the same wording form as for SVN.

2025-02-12 16:47 UTC, deeglaze commented on draft-ietf-rats-corim.md
> +A Linear Privilege Level describes an operating privilege for the target environment.
Please clarify.

2025-02-12 16:48 UTC, deeglaze commented on draft-ietf-rats-corim.md
> +*  If the condition ECT value for `measurement-values-map` codepoint 15 is an untagged `int` or an `int` tagged with #6.564 then an equality comparison is performed on the `int` components.
Fixed.

2025-02-12 19:17 UTC, nedmsmith commented on draft-ietf-rats-corim.md
> +If the entry `linear-privilege-type-choice` is an `int-range` or `int-range` tagged with #6.564, then comparison with the pair of `inf-int` values MINPRIV and MAXPRIV is as follows.
`inf-int` doesn't appear to be defined anywhere.

2025-02-12 19:25 UTC, nedmsmith commented
General feedback: The value of an integer measurement type that is strictly used for privilege levels doesn't allow the flexibility to be used for other measurement types (as in the type mechanism isn't extensible) means it isn't as generally useful. I thought we were going to give it semantics that were similar to raw-value where the mkey tag can be used to distginguish semantic richness while the appraisal comparison doesn't care as it's simple checking whether a singleton value falls within the range of integers.

2025-02-13 01:34 UTC, deeglaze commented
> General feedback: The value of an integer measurement type that is strictly used for privilege levels doesn't allow the flexibility to be used for other measurement types (as in the type mechanism isn't extensible) means it isn't as generally useful.

Agreed, which is why the tagged value is a tagged-int-range, and not a tagged-linear-privilege-range. The added semantic context of linear privilege comes from codepoint 15. An mkey can add further context that it's for a specific notion of privilege like CPL or VMPL.

> I thought we were going to give it semantics that were similar to raw-value where the mkey tag can be used to distginguish semantic richness while the appraisal comparison doesn't care as it's simple checking whether a singleton value falls within the range of integers.

The comparison only cares so much as it provides the semantics of range inclusion.

2025-02-13 01:38 UTC, deeglaze commented on cddl/linear-privilege-level.cddl
> +int-range = [min: inf-int, max: inf-int]
It's a weak form of comparison for use in conditional endorsements. We have SVN range comparisons. This is just slightly broader.

2025-02-13 01:38 UTC, deeglaze commented on draft-ietf-rats-corim.md
> +If the entry `linear-privilege-type-choice` is an `int-range` or `int-range` tagged with #6.564, then comparison with the pair of `inf-int` values MINPRIV and MAXPRIV is as follows.
Fixed.

2025-02-28 15:50 UTC, nedmsmith approved these changes

2025-02-28 16:37 UTC, yogeshbdeshpande commented on draft-ietf-rats-corim.md
> +The full range if signed integers may be used.
```suggestion
The full range of signed integers may be used.
```

2025-02-28 16:40 UTC, yogeshbdeshpande commented on draft-ietf-rats-corim.md
> +*  If the condition ECT value for `measurement-values-map` codepoint 15 is an `int` then the comparison MUST return true if and only if MINPRIV and MAXPRIV are equal and finite.
What is MINPRIV and MAXPRIV here, please set the context, like you did for PRIV Above.

Just say they are constant with Value X or Value Y.

2025-02-28 16:42 UTC, yogeshbdeshpande commented on draft-ietf-rats-corim.md
> +If the entry `linear-privilege-type-choice` is an `int-range` or `int-range` tagged with #6.564, then comparison with the pair of `opt-int` values MINPRIV and MAXPRIV is as follows.
I find it hard to understand the logic for 2539 beneath.. Is there a way to simplify/clarify it better??

2025-02-28 16:42 UTC, yogeshbdeshpande reviewed
Request please check!

2025-02-28 17:09 UTC, nedmsmith commented on draft-ietf-rats-corim.md
> +*  If the condition ECT value for `measurement-values-map` codepoint 15 is an `int` then the comparison MUST return true if and only if MINPRIV and MAXPRIV are equal and finite.
If I reread the text above using MAXINT/MININT the wording seems confusing in that max infinity can't be equal to min infinity and infinity can be equal to a finite number at the same time. Or at least I have to be a theoretical mathematition to make it make sense. 

I think the text is trying to say that if the input value is type 'int' then the comparison must exactly match a value that is also of type 'int'. It is noted that MAXINT and MININT are special case values of type 'int' because we don't want to encode large numbers.

2025-02-28 19:00 UTC, deeglaze commented on draft-ietf-rats-corim.md
> +*  If the condition ECT value for `measurement-values-map` codepoint 15 is an `int` then the comparison MUST return true if and only if MINPRIV and MAXPRIV are equal and finite.
I've changed the wording. Please take a look.

2025-03-01 00:19 UTC, nedmsmith approved these changes
LGTM

2025-03-04 17:06 UTC, deeglaze commented
@yogeshbdeshpande need any more changes or look good?

2025-03-04 17:24 UTC, yogeshbdeshpande commented
> @yogeshbdeshpande need any more changes or look good?

Thanks for the changes, checking now.........

2025-03-04 17:32 UTC, yogeshbdeshpande approved these changes
LGTM

2025-03-04 17:33 UTC, yogeshbdeshpande commented
Thanks for making the suggested changes, this is much clear now and request @thomas-fossati and @henkbirkholz also to review this.... 

I am happy with the clarification and have now approved the PR.

2025-03-05 18:04 UTC, nedmsmith approved these changes
LGTM

2025-03-07 16:27 UTC, nedmsmith approved these changes
LGTM

2025-03-17 19:33 UTC, deeglaze commented
Is this good to merge? @henkbirkholz @thomas-fossati @andrew-draper

2025-03-18 09:47 UTC, thomas-fossati commented on cddl/raw-integral-type-choice.cddl
> +integral = int / #6.2(bytes) / #6.3(bytes)
maybe, to make the CDDL more transparent to the readers:
```suggestion
biguint = #6.2(bytes)
bignint = #6.3(bytes)
bigint = biguint / bignint
integer = int / bigint
```
or (more condensed):
```suggestion
bigint = #6.2(bytes) / #6.3(bytes)
integer = int / bigint
```

2025-03-18 09:47 UTC, thomas-fossati commented on draft-ietf-rats-corim.md
> +A raw integral is represented with either major type 0 or major type 1 ints, or even tagged bignums.
What is the use case for bignums?

2025-03-18 09:47 UTC, thomas-fossati commented on cddl/raw-integral-type-choice.cddl
> +raw-integral-type-choice /= integral / tagged-integral-range
we are defining `raw-integral-type-choice` here for good:
```suggestion
raw-integral-type-choice = integral / tagged-integral-range
```

2025-03-18 09:47 UTC, thomas-fossati commented on cddl/raw-integral-type-choice.cddl
> +opt-integral = integral / null
What does “opt” stand for?  Optional?  If so, it sounds a bit odd.

What about a bit more expressively:

```
integer-range = [min: integer / negative-inf, max: integer / positive-inf]

negative-inf = null
positive-inf = null
```

2025-03-18 09:47 UTC, thomas-fossati commented on cddl/cbor-tags.txt
> +tagged-integral-range = #6.564(int-range)
This probably needs regenerating - it’s called `integral-range` below.

2025-03-18 09:47 UTC, thomas-fossati commented on draft-ietf-rats-corim.md
> +Consider an `integral` ACS entry value named ENTRY in a `measurement-values-map` codepoint (e.g., 15) that allows comparing `integral` against a either another `integral` or an `integral-range` named
```suggestion
Consider an `integral` ACS entry value named ENTRY in a `measurement-values-map` codepoint (i.e., 15) that allows comparing `integral` against either another `integral` or an `integral-range` named CONDITION.
```

2025-03-18 09:47 UTC, thomas-fossati commented on draft-ietf-rats-corim.md
> +*  If CONDITION is an `integral-range` tagged with #6.564, then a range inclusion comparison is performed.
```suggestion
*  If CONDITION is an `integral-range` (CBOR tag 564), then a range inclusion comparison is performed.
```

2025-03-18 09:47 UTC, thomas-fossati commented on draft-ietf-rats-corim.md
> +    + CONDITION.min is `null` or ENTRY is greater than or equal to the CONDITION.min.
```suggestion
    + CONDITION.min is `null` or ENTRY is greater than or equal to CONDITION.min.
```

2025-03-18 09:47 UTC, thomas-fossati commented on draft-ietf-rats-corim.md
> +Consider an `integral-range` or `integral-range` tagged with #6.564 value named ENTRY in a `measurement-values-map` codepoint (e.g., 15) that allows comparing an `int-range` against either another `i
```suggestion
Consider an `integral` or `integral-range` (CBOR tag 564) value named ENTRY in a `measurement-values-map` codepoint (i.e., 15) that allows comparing an `integral-range` against either another `integral-range` or an `integral` named CONDITION.
```

2025-03-18 09:47 UTC, thomas-fossati commented on draft-ietf-rats-corim.md
> +*  If CONDITION is an `integral-range` tagged with #6.564, then a range subsumption comparison is performed (i.e., the condition range includes all values of the entry range).
```suggestion
*  If CONDITION is an `integral-range` (CBOR tag 564), then a range subsumption comparison is performed (i.e., the condition range includes all values of the entry range).
```

2025-03-18 18:36 UTC, nedmsmith approved these changes
LGTM

2025-03-18 18:36 UTC, nedmsmith commented on draft-ietf-rats-corim.md
> +Consider an `integral-range` or `integral-range` tagged with #6.564 value named ENTRY in a `measurement-values-map` codepoint (e.g., 15) that allows comparing an `int-range` against either another `i
Is the justification for changing 'int' to 'integral' because the numeric is defined in terms of int, uint, and big integers?

2025-03-18 18:36 UTC, nedmsmith commented on draft-ietf-rats-corim.md
> +A raw integral is represented with either major type 0 or major type 1 ints, or even tagged bignums.
I have this question also. For example, when would someone use bigint vs. raw-value (which is bytes also) assuming a future version of raw-value could introduce a range of raw-value?

2025-03-19 14:24 UTC, deeglaze commented on draft-ietf-rats-corim.md
> +Consider an `integral` ACS entry value named ENTRY in a `measurement-values-map` codepoint (e.g., 15) that allows comparing `integral` against a either another `integral` or an `integral-range` named
This is not the intention for int-range. Any entry that chooses to use tagged-int-range (i.e., "allows comparing") is to use these comparison rules.

2025-03-19 14:25 UTC, deeglaze commented on draft-ietf-rats-corim.md
> +Consider an `integral-range` or `integral-range` tagged with #6.564 value named ENTRY in a `measurement-values-map` codepoint (e.g., 15) that allows comparing an `int-range` against either another `i
Will remove bigint and just say raw-int for simplicity.

2025-03-19 18:46 UTC, nedmsmith approved these changes
LGTM - assuming the build issues get resolved.

2025-03-20 03:08 UTC, thomas-fossati approved these changes
LGTM

2025-03-20 03:08 UTC, thomas-fossati commented on draft-ietf-rats-corim.md
> +Consider an `int` ACS entry value named ENTRY in a `measurement-values-map` codepoint (e.g., 15) that allows comparing `int` against a either another `int` or an `int-range` named CONDITION.
```suggestion
Consider an `int` ACS entry value named ENTRY in a `measurement-values-map` codepoint (e.g., 15) that allows comparing `int` against either another `int` or an `int-range` named CONDITION.
```

2025-03-26 15:12 UTC, merged